### ISSUE TITLE
Put limits to the zooming and panning

### ISSUE THREAD

**Issue by JohannesLipp** [Semantic-Society/Neologism#30]
Currently we have an infinite canvas, without limits on scrolling.
This can lead to strange situations, like users accidentally or on purpose putting classes very far from the visible model. See also #29

**Comment by JohannesLipp** [comment]
Also note #29

**Comment by JohannesLipp** [comment]
Please also think of adding +/- buttons for zooming, and a "center vocab" button. Possibly, additional buttons for navigation (left, right, up, down) could be useful.

**Comment by husaynali** [comment]
To further this, I do find the need to address Michael's concern (from the note on issue 29) and I quote 

> Should we just make sure that the everything is visible when opening a vocabulary?

Otherwise, I don't see the idea of rearranging the elements intuitive to fit the viewport when the user deliberately draws it farther.

Also, we would soon have the zoomIn, out, and reset to default zoom controls.

**Comment by JohannesLipp** [comment]
Thanks @husaynali ! Since the recently added "reset" button will reset both zoom level and panning (position), we do not have to limit the zoom levels here.
