### ISSUE TITLE
Create default namespace for new vocab

### ISSUE THREAD

**Issue by JohannesLipp** [Semantic-Society/Neologism#62]
Some users do not like to think of a namespace name. Create some default namespace, like <hostname>/vocab/<vocab name or hash>, to ease that process for users.

**Comment by husaynali** [comment]
@JohannesLipp Please elaborate taking assistance of the form image below for creating a new vocabulary. Since the current vocabulary form has a field for the complete URI and not prefix+namespace. Do you mean autocomplete the namespace as the users start to input the URI but then I believe the fields in the form should be separated for both URI and prefix
![image](https://user-images.githubusercontent.com/8904368/96805051-fb1dd280-1410-11eb-88ba-094cdf334bce.png)

**Comment by JohannesLipp** [comment]
The process would be:

- The user enters the vocab name
- The system auto-fills the vocab URI with `http://w3id.org/neologism/{vocab name}#`
- The user can of course still edit that vocab URI

**Comment by husaynali** [comment]
{vocab name} would be lowercase*
