### ISSUE TITLE
Select/edit property by clicking the arc instead of its source/subject node

### ISSUE THREAD

**Issue by husaynali** [Semantic-Society/Neologism#76]
Open the edit/view popup when you click on an edge itself.

**Comment by husaynali** [comment]
Blocked by #97

**Comment by husaynali** [comment]
@JohannesLipp few things remain unclear
1. how to select between multiple props between two nodes? (currently, the arc shows concatenated prop names as string)
2. While rendering the props, A merge func merges the props replacing original ID with the source ID which makes impossible to refer a property for edit in pop up box
3. How shall we select an individual/multiple prop with such a setting?

**Comment by husaynali** [comment]
One way to do is the following

1. while merging, keep props orig ID combined by a separator (for multiple case)
2. then on edit single case is usual, for multiple cases show a drop-down to select props to edit by their name or ID as an option

**Comment by JohannesLipp** [comment]
You are right, we did not think of this case before. Since multiple props between nodes are not too likely, a simple approach would suffice. Another option compared to a drop-down menu would be to render the arcs individually. I assume this is more work though. 

Résumé: Your drop-down menu sounds good, we should go with that. Thanks!
